# TODO: finish this
# TODO: finish also dockerfiles for ELK. Don't do a dashboard container, we will use kibana.
# TODO: Send data to ELK directly instead of saving them to disk, replace all read_csv, to_csv methods
# TODO: Needs a new class to send and receive time-series from the ELK
# TODO: Create Kibana dashboards replacing the dashboard.
# TODO: The new folder structure is not tested probably imports will not work.

FROM python:3.7.6
#
RUN apt-get update
RUN apt-get -y install python3-dev
RUN apt-get -y install default-libmysqlclient-dev
RUN apt-get -y install build-essential
#
#
RUN mkdir /project
COPY ./pyproject.toml /project
COPY ./poetry.lock /project
COPY Makefile /project
COPY code /project


#
#RUN pip install -U pip
#RUN pip install -r requirements.txt --extra-index-url https://www.piwheels.org/simple
#RUN pip install mysqlclient==1.4.6
#
#CMD python ./Fetcher.py
